name: blood_pressure_app
description: Track your blood pressure wherever you go
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0  # MIT
  sqflite:  # BSD-2-Clause
  path:  # BSD-3-Clause

  intl: ^0.18.0  # BSD-3-Clause
  fl_chart: ^0.63.0  # MIT
  share_plus: ^7.0.1  # BSD-3-Clause
  flutter_material_color_picker: ^1.2.0  # MIT
  csv: ^5.0.2  # MIT
  url_launcher: ^6.1.11  # BSD-3-Clause
  shared_preferences: ^2.1.1  # BSD-3-Clause
  pdf: ^3.10.4
  package_info_plus: ^4.0.2

  # can become one custom dependency
  file_saver: ^0.2.1  # BSD-3-Clause
  file_picker: ^5.2.11  # MIT
  jsaver: ^1.2.0
  function_tree: ^0.8.13
  badges: ^3.1.1
  flutter_markdown: ^0.6.17
  collection: ^1.17.1
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  file: any
  flutter_lints: ^2.0.0
  mockito: ^5.4.1

flutter:
  uses-material-design: true
  generate: true

