name: blood_pressure_app
description: Track your blood pressure wherever you go
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.6.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  csv: ^5.0.2
  collection: ^1.17.1
  intl: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17
  fl_chart: ^0.63.0
  function_tree: ^0.9.0
  provider: ^6.0.0
  path:
  pdf: ^3.10.4
  package_info_plus: ^4.0.2
  sqflite:
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

  # can become one custom dependency
  file_picker: ^5.2.11  # MIT
  jsaver: ^1.2.0
  restart_app: ^1.2.1
  fluttertoast: ^8.2.4

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  sqflite_common_ffi: ^2.3.0
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true
  generate: true

