name: health_data_store
description: A package to easily store health related data.
version: 1.0.0+2
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  sqflite_common: ^2.5.4

dev_dependencies:
  build_runner: ^2.4.8
  coverage: ^1.8.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  sqflite_common_ffi: ^2.1.1+1
  test: ^1.25.2

