name: "Bug Report"
description: Create a new ticket for a bug.
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Everything after here is not required, but might be helpful to think about."
  - type: input
    id: device_version
    attributes:
      label: "Android version"
      description: Enter your device version
      placeholder: Android 14
    validations:
      required: false
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: If you want to, you can briefly write how to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots & Settings backup"
      description: Some bugs are easier to understand/reproduce when the correct settings are provided. If you want to, you can add screenshots to help explain your problem.
      render: bash
    validations:
      required: false
  - type: textarea
    id: app_debug_info
    attributes:
      label: "App debug info"
      description: Information about app version and Settings.
      placeholder: You can copy the information through the version page at the end of the settings list.
      render: bash
    validations:
      required: false
