name: "Bug Report"
description: Use this template to report bugs in the app.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. The following questions will
        guide you through different aspects of your problems and help us 
        to understand the issue and reproduce it. Of course you can omit details
        as you see fitting.
        
        Please check if there is already an issue for your bug. You may need to 
        look through closed issues as issues get closed as soon as the fix is in
        the source code.

  - type: input
    id: app-version
    attributes:
      label: App version
      placeholder: v1.7.1
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the issue you're experiencing."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "Please list the steps to reproduce the issue."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: markdown
    attributes:
      value: |
        ### Attachments
        Please upload screenshots that help to illustrate what happened, debug
        info from the version page in the settings and any logs the app produced
        here.
        
        With some issues uploading an backup of your app settings is also 
        helpful. But please note that some information like entered medications
        and age could be reconstructed from that data.

  - type: textarea
    id: logs_and_files
    attributes:
      label: Details (Screenshots, Debug info, Configurations)
      value: |
        <details><summary>Attachments</summary>
        
        
        
        </details>
