name: app-CI

on:
  push:
    branches:
      - 'main'
    paths:
      - "app/**"
      - "health_data_store/**"
      - ".github/workflows/app-CI.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # ensures there are no unexpected directories needed
        sparse-checkout: |
          app
          health_data_store
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        # flutter-version: '3.18.0-0.2.pre'
        channel: 'beta'
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./app
    - name: Run tests
      run: flutter test
      working-directory: ./app

  build-android:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        # flutter-version: '3.18.0-0.2.pre'
        channel: 'beta'
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./app
    
    - name: Build apk
      run: flutter build apk --flavor github --debug
      working-directory: ./app
