name: '📱 Application'

on:
  push:
    branches:
      - 'main'
    paths:
      - "app/**"
      - "health_data_store/**"
      - ".github/workflows/app-CI.yml"
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: 'beta'
  DART_SDK: 'beta'
  JAVA_VERSION: '17'

jobs:
  test:
    name: "🧪 Run test"
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # ensures there are no unexpected directories needed
        sparse-checkout: |
          app
          health_data_store
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ env.DART_SDK }}
    - name: Generate code
      run: dart pub get
      working-directory: ./health_data_store
    - name: Generate code
      run: dart run build_runner build
      working-directory: ./health_data_store

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./app
    - name: Run tests
      run: flutter test
      working-directory: ./app

  build-android:
    name: "🛠️ Build Android"
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ env.JAVA_VERSION }}
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ env.DART_SDK }}
    - name: Generate code
      run: dart pub get
      working-directory: ./health_data_store
    - name: Generate code
      run: dart run build_runner build
      working-directory: ./health_data_store

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
    - name: Get dependencies
      run: flutter pub get
      working-directory: ./app
    
    - name: Build apk
      run: flutter build apk --flavor github --debug
      working-directory: ./app
