name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - "app/**"
      - ".github/workflows/CI.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.18.0-0.2.pre'
        channel: 'beta'
    - run: flutter pub get
      working-directory: ./app
    - run: flutter test
      working-directory: ./app

  build-android:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.18.0-0.2.pre'
        channel: 'beta'
    - run: flutter pub get
      working-directory: ./app
    
    - run: flutter build apk --flavor github --debug
      working-directory: ./app
