name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - "lib/**"
      - "android/**"
      - "assets/**"
      - "linux/**"
      - "windows/**"
      - ".github/workflows/CI.yml"

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
    - run: flutter pub get
    - run: flutter test

  build-android:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
    - run: flutter pub get
    
    - run: flutter build apk --flavor github --debug