name: Generate and Deploy Coverage Report

on:
  workflow_run:
    workflows:
      - '📱 Application'
      - '📦 Packages'
    types:
      - completed

jobs:
  generate-deploy-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download app coverage
        uses: actions/download-artifact@v3
        with:
          name: app-coverage
          path: coverage/app

      - name: Download health data store coverage
        uses: actions/download-artifact@v3
        with:
          name: health_data_store-coverage
          path: coverage/health_data_store

      - name: Combine Coverage Reports
        run: |
          mkdir -p coverage/combined
          cat coverage/app/lcov.info coverage/health_data_store/coverage.lcov > coverage/combined/lcov.info

      - name: Generate HTML Report
        run: |
          npm install -g lcov-report
          lcov-report -i coverage/combined/lcov.info -o coverage/combined

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage/combined