name: Build and deploy developer docs
# Disabled until a solution for mono repos is found
on:
    #push:
    #    branches:
    #       - "main"
    #    paths:
    #       - "lib/**"
    #       - "README.md"
    workflow_dispatch:
jobs:
    build-docs:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:       
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Dart
          uses: dart-lang/setup-dart@v1

        - name: Load packages
          working-directory: ./app
          run: dart pub get

        - name: Run Dartdoc
          working-directory: ./app
          run: dart doc .

        - name: Upload API documentation artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: './app/doc/api/'

    deploy-docs:
        permissions:
          contents: read
          pages: write
          id-token: write
        runs-on: ubuntu-latest
        needs: build-docs
        environment:
          name: github-pages
          url: ${{steps.deployment.outputs.page_url}}
        steps:
          - name: Deploy artifact
            id: deployment
            uses: actions/deploy-pages@v1

