name: '📋 Fastlane'
on:
  push:
    branches:
    - '**'
    paths:
      - "fastlane/**"
      - ".github/workflows/fastlane-meta.yml"
  pull_request:
    branches:
    - '**'
    paths:
      - "fastlane/**"
      - ".github/workflows/fastlane-meta.yml"
  workflow_dispatch:
    
jobs:
  validate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            sparse-checkout: |
              fastlane
        - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2