name: '📦 Packages'

on:
  push:
    branches:
      - 'main'
    paths:
      - "health_data_store/**"
      - ".github/workflows/pkg-CI.yml"
  workflow_dispatch:

env:
  DART_SDK: 'beta'

jobs:
  test-health_data_store:
    name: '🧪 Test'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # ensures there are no unexpected directories needed
        sparse-checkout: |
          health_data_store
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ env.DART_SDK }}

    - name: Get dependencies
      run: dart pub get
      working-directory: ./health_data_store
    - name: Generate code
      run: dart run build_runner build
      working-directory: ./health_data_store
    - name: Analyze code
      run: dart analyze
      working-directory: ./health_data_store
    - name: Run tests
      run: dart test
      working-directory: ./health_data_store
